name: mida
version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    restart: always
    privileged: true
    user: root
    command:
      - nginx-debug
      - '-g'
      - daemon off;
    environment:
      - ENV=development
    networks:
      - midacloud
    ports:
      - 80:80
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service-gateway

  service-gateway:
    image: midacloud:5000/midacloud-service-gateway:latest
    hostname: '{{.Node.Hostname}}'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: always
        delay: 5s
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_ACCESS_TOKEN_SECRET=secret
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=1h
      - JWT_REFRESH_TOKEN_SECRET=secret
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=20d
      - DB_HOST=postgres.midacloud
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_SYNCHRONIZE=true
      - DB_DROP_SCHEMA=false
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_ENDPOINT=http://aws.midacloud:4566
      - REDIS_HOST=redis.midacloud
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MAILER_QUEUE_URL=http://aws.midacloud:4566/000000000000/mail-queue
      - MONGO_URL=mongodb://mongo.midacloud:27017
      - RABBITMQ_URL=amqp://rabbitmq.midacloud:5672
      - RABBITMQ_QUEUE=gateway_queue
    ports:
      - 3000
    networks:
      - midacloud

  service-mailer:
    image: midacloud:5000/midacloud-service-mailer:latest
    hostname: '{{.Node.Hostname}}'
    deploy:
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s
    environment:
      - NODE_ENV=production
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_ENDPOINT=http://aws.midacloud:4566
      - MAILER_HOST=mail.midacloud
      - MAILER_PORT=1025
      - MAILER_USERNAME=local
      - MAILER_PASSWORD=local
      - MAILER_QUEUE_URL=http://aws.midacloud:4566/000000000000/mail-queue
      - MAILER_POOLING_INTERVAL=5s
      - MAILER_POOLING_SIZE=10
      - MONGO_URL=mongodb://mongo.midacloud:27017
      - RABBITMQ_URL=amqp://rabbitmq.midacloud:5672
      - RABBITMQ_QUEUE=mailer_queue
    ports:
      - 3000
    networks:
      - midacloud

  service-account:
    image: midacloud:5000/midacloud-service-account:latest
    hostname: '{{.Node.Hostname}}'
    deploy:
      replicas: 2
      restart_policy:
        condition: always
        delay: 5s
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_ACCESS_TOKEN_SECRET=secret
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=1h
      - JWT_REFRESH_TOKEN_SECRET=secret
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=20d
      - DB_HOST=postgres.midacloud
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_SYNCHRONIZE=true
      - DB_DROP_SCHEMA=false
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_ENDPOINT=http://aws.midacloud:4566
      - REDIS_HOST=redis.midacloud
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MAILER_QUEUE_URL=http://aws.midacloud:4566/000000000000/mail-queue
      - MONGO_URL=mongodb://mongo.midacloud:27017
      - RABBITMQ_URL=amqp://rabbitmq.midacloud:5672
      - RABBITMQ_QUEUE=account_queue
    ports:
      - 3000
    networks:
      - midacloud
    depends_on:
      - service-mailer

networks:
  midacloud:
    external: true
